name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend on server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          timeout: 60s
          command_timeout: 20m

          script: |
            set -e
            echo "Go to backend directory"
            cd /home/baridik/apps/backend
            echo "Current path:"
            pwd
            echo "Pull latest code"
            git fetch origin main
            git reset --hard origin/main
            echo "Restore packages"
            dotnet restore BaridikExpress/BaridikExpress.Api.csproj
            echo "Build backend"
            dotnet build BaridikExpress/BaridikExpress.Api.csproj -c Release --no-restore
            echo "Restart backend service"
            sudo -n systemctl restart baridik-backend
            echo "Check backend service"
            sudo -n systemctl status baridik-backend
            echo "Backend deployed successfully"
