name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend on server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            cd ${{ secrets.DEPLOY_DIR }}

            echo "Current path:"
            pwd

            echo "Pull latest code"
            git pull origin main

            echo "Restore packages"
            dotnet restore BaridikExpress.sln

            echo "Build backend"
            dotnet build BaridikExpress.sln -c Release --no-restore

            echo "Restart backend service"
            sudo -n systemctl restart baridik-backend

            echo "Check backend service"
            sudo -n systemctl status baridik-backend --no-pager

            echo "Deployment completed"
